name: element_key_inspector
description: "A Flutter package that allows you to visually inspect and highlight widgets by their keys in your app. Ideal for test automation workflows."
version: 0.0.2
homepage: https://github.com/buyandship/element_key_inspector

environment:
  sdk: ^3.5.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: false
